# Generated by Django 4.2 on 2023-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_dusty',
            field=models.BooleanField(default=False, verbose_name='Чи прийнято'),
        ),
    ]
