# Generated by Django 4.2 on 2023-04-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_order_comment_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='season_ticket_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id абонемента'),
        ),
    ]
