# Generated by Django 4.2 on 2023-04-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_alter_order_season_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='season_ticket_id',
            field=models.IntegerField(blank=True, default=1, verbose_name='Id абонемента'),
            preserve_default=False,
        ),
    ]
